apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-control-plane
  namespace: aurora-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aurora
  template:
    metadata:
      labels:
        app: aurora
    spec:
      serviceAccountName: aurora-sa
      containers:
      - name: aurora
        image: aayud/aurora-platform:latest
        ports:
        - containerPort: 8000
